config/routes.rb
English::Application.routes.draw do
  scope module: :web do
    root 'videos#index'
    resources :videos, only: [:index, :show]

    namespace :admin do
      root 'videos#index'
      resources :subtitles
      resources :videos
    end
  end
end

app/models/subtitle.rb
class Subtitle < ActiveRecord::Base
  belongs_to :video

  state_machine initial: :active do
    state :active
    state :deleted

    event :restore do
      transition all => :active
    end

    event :mark_as_deleted do
      transition all => :deleted
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :subtitle

  state_machine initial: :active do
    state :active
    state :deleted

    event :restore do
      transition all => :active
    end

    event :mark_as_deleted do
      transition all => :deleted
    end
  end

  include VideoRepository
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def app_config
    Rails.application.config
  end
end

app/controllers/web/admin/application_controller.rb
class Web::Admin::ApplicationController < Web::ApplicationController
end

app/controllers/web/admin/subtitles_controller.rb
class Web::Admin::SubtitlesController < Web::Admin::ApplicationController
  def index
    @q = Subtitle.ransack(params[:q])
    @subtitles = @q.result.page(params[:page]).per(app_config.pagination[:per_page])
  end

  def new
    @subtitle = Subtitle.new
  end

  def edit
    @subtitle = Subtitle.find(params[:id])
  end

  def create
    @subtitle = SubtitleEditType.new(params[:subtitle])

    if @subtitle.save
      redirect_to admin_subtitles_path
    else
      render action: 'new'
    end
  end

  def update
    @subtitle = SubtitleEditType.find(params[:id])
    if @subtitle.update(params[:subtitle])
      redirect_to admin_subtitles_path
    else
      render action: 'edit'
    end
  end

  def destroy
    subtitle = Subtitle.find(params[:id])
    subtitle.mark_as_deleted
    redirect_to admin_subtitles_path
  end
end

app/controllers/web/admin/videos_controller.rb
class Web::Admin::VideosController < Web::Admin::ApplicationController
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result.page(params[:page]).per(app_config.pagination[:per_page])
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = VideoEditType.new(params[:video])

    if @video.save
      redirect_to admin_videos_path
    else
      render action: 'new'
    end
  end

  def update
    @video = VideoEditType.find(params[:id])
    if @video.update(params[:video])
      redirect_to admin_videos_path
    else
      render action: 'edit'
    end
  end

  def destroy
    video = Video.find(params[:id])
    video.mark_as_deleted
    redirect_to admin_videos_path
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
end

app/controllers/web/videos_controller.rb
class Web::VideosController < Web::ApplicationController
  def index
    @q = Video.active.ransack(params[:q])
    @videos = @q.result.page(params[:page]).per(app_config.pagination[:per_page])
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtitles_helper.rb
module SubtitlesHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Starter Template for Bootstrap
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      .navbar-header
        %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => ".navbar-collapse"} }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to t('.title'), root_path, :class => "navbar-brand"
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            = link_to t('.videos'), videos_path
          %li
            = link_to t('.admin'), admin_root_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
          %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
          = msg
      = yield

app/views/web/admin/subtitles/_form.html.haml
= simple_form_for [:admin, @subtitle], html: { class: 'form-horizontal' } do |f|
  = f.error_notification
  = f.input :lang
  = f.input :source
  = f.association :video

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('helpers.links.cancel'), admin_subtitles_path, :class => 'btn'

app/views/web/admin/subtitles/edit.html.haml
.page-header
  %h1=t '.title'
= render :partial => "form"

app/views/web/admin/subtitles/index.html.haml
.page-header
  %h1=t '.title'

.action-toolbox.clearfix
  = link_to t('.new'), new_admin_subtitle_path, class: 'btn btn-primary pull-right'

- if @subtitles.present?
  %table.table.table-striped
    %thead
      %tr
        %th.subtitle.subtitle_id= 'id'
        %th.subtitle.subtitle-land= 'lang'
        %th.subtitle.subtitle-state= 'state'
        %th.subtitle.subtitle-action= 'action'
    %tbody
      - @subtitles.each do |subtitle|
        %tr
          %td= subtitle.id
          %td= subtitle.lang
          %td= subtitle.state
          %td.btn-lg
            = link_to edit_admin_subtitle_path(subtitle.id) do
              %span.glyphicon.glyphicon-pencil
            - if subtitle.deleted?
              = link_to admin_subtitle_path(subtitle, subtitle: { state_event: :restore }), method: :patch do
                %span.glyphicon.glyphicon-share-alt
            - else
              = link_to admin_subtitle_path(subtitle), method: :delete do
                %span.glyphicon.glyphicon-trash

  = paginate @subtitles, :remote => true
- else
  = t('.no_data')

app/views/web/admin/subtitles/new.html.haml
.page-header
  %h1=t '.title'
= render :partial => "form"

app/views/web/admin/videos/_form.html.haml
= simple_form_for [:admin, @video], html: { class: 'form-horizontal' } do |f|
  = f.error_notification
  = f.input :title
  = f.input :slug
  = f.input :description
  = f.input :sourcecode

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('helpers.links.cancel'), admin_videos_path, :class => 'btn'

app/views/web/admin/videos/index.html.haml
.page-header
  %h1=t '.title'

.action-toolbox.clearfix
  = link_to t('.new'), new_admin_video_path, class: 'btn btn-primary pull-right'

- if @videos.present?
  %table.table.table-striped
    %thead
      %tr
        %th.video.video_id= 'id'
        %th.video.video-title= 'title'
        %th.video.video-state= 'state'
        %th.video.video-action= 'action'
    %tbody
      - @videos.each do |video|
        %tr
          %td= video.id
          %td= video.title
          %td= video.state
          -#%td
          -#  %a.btn.btn-info.nowrap{ "href" => '' }
          -#    %span.glyphicon.glyphicon-edit
          -#  %a.btn.btn-danger.nowrap{ "href" => '' }
          -#    %span.glyphicon.glyphicon-trash
          %td.btn-lg
            = link_to edit_admin_video_path(video.id) do
              %span.glyphicon.glyphicon-pencil
            - if video.deleted?
              = link_to admin_video_path(video, video: { state_event: :restore }), method: :patch do
                %span.glyphicon.glyphicon-share-alt
            - else
              = link_to admin_video_path(video), method: :delete do
                %span.glyphicon.glyphicon-trash

  = paginate @videos, :remote => true
- else
  = t('.no_data')

app/views/web/videos/index.html.haml
.page-header
  %h1=t '.title'

- if @videos.present?
  %table.table.table-striped
    %thead
      %tr
        %th.video.video-title= 'title'
    %tbody
      - @videos.each do |video|
        %tr
          %td= video.title

  = paginate @videos, :remote => true
- else
  = t('.no_data')